-- GENERATED by scripts/gen_seed.py — reference data from the official program posters
-- and the Volleyball 1st Physical Testing report.

insert into public.facilities (slug, name, description, sort) values
  ('gymnasium', 'Gymnasium', 'Main indoor court — futsal, basketball, volleyball, badminton, table tennis', 0),
  ('fitness-center', 'Fitness Center', 'Cardio and strength equipment', 1),
  ('soccer-field', 'Soccer Field (Annex)', 'Football, rugby and American football', 2),
  ('martial-arts-room', 'Martial Arts Room', 'Boxing, fight camp and kickboxing', 3),
  ('swimming-pool', 'Swimming Pool', 'Indoor pool', 4),
  ('padel-court', 'Padel Court', 'Bookable same-day outside program hours', 5),
  ('tennis-court-1', 'Tennis Court 1', 'Bookable same-day', 6),
  ('tennis-court-2', 'Tennis Court 2', 'Bookable same-day', 7),
  ('old-weight-room', 'Old Weight Room (Old Fitness Room)', 'Secondary training room used by teams on alternate days', 8);

insert into public.teams (name, sport, gender) values
  ('Women''s Futsal', 'Futsal', 'women'),
  ('Men''s Futsal', 'Futsal', 'men'),
  ('Women''s Basketball', 'Basketball', 'women'),
  ('Men''s Basketball', 'Basketball', 'men'),
  ('Women''s Volleyball', 'Volleyball', 'women'),
  ('Men''s Volleyball', 'Volleyball', 'men'),
  ('Badminton', 'Badminton', 'mixed'),
  ('Table Tennis', 'Table Tennis', 'mixed'),
  ('Boxing Club', 'Boxing', 'mixed'),
  ('Fight Camp', 'MMA / Fight Camp', 'mixed'),
  ('Kick Boxing', 'Kickboxing', 'mixed'),
  ('Padel', 'Padel', 'mixed'),
  ('Football Team A', 'Football', 'mixed'),
  ('Football Team B', 'Football', 'mixed'),
  ('Rugby', 'Rugby', 'mixed'),
  ('American Football', 'American Football', 'mixed');

insert into public.facility_schedule (facility_id, day_of_week, start_time, end_time, activity, team_id, note)
select f.id, v.d, v.s::time, v.e::time, v.act, t.id, v.note from (values
  ('gymnasium', 1, '14:30', '16:00', 'Women''s Futsal', 'Women''s Futsal', null),
  ('old-weight-room', 2, '14:30', '16:00', 'Women''s Futsal', 'Women''s Futsal', null),
  ('gymnasium', 3, '14:30', '16:00', 'Women''s Futsal', 'Women''s Futsal', null),
  ('old-weight-room', 4, '14:30', '16:00', 'Women''s Futsal', 'Women''s Futsal', null),
  ('gymnasium', 5, '14:30', '16:00', 'Women''s Futsal', 'Women''s Futsal', null),
  ('gymnasium', 1, '22:00', '23:00', 'Men''s Futsal', 'Men''s Futsal', 'End time not listed on the official poster'),
  ('old-weight-room', 2, '22:00', '23:00', 'Men''s Futsal', 'Men''s Futsal', 'End time not listed on the official poster'),
  ('gymnasium', 3, '22:00', '23:00', 'Men''s Futsal', 'Men''s Futsal', 'End time not listed on the official poster'),
  ('old-weight-room', 4, '22:00', '23:00', 'Men''s Futsal', 'Men''s Futsal', 'End time not listed on the official poster'),
  ('gymnasium', 5, '22:00', '23:00', 'Men''s Futsal', 'Men''s Futsal', 'End time not listed on the official poster'),
  ('old-weight-room', 1, '16:00', '17:30', 'Women''s Basketball', 'Women''s Basketball', null),
  ('gymnasium', 2, '16:00', '17:30', 'Women''s Basketball', 'Women''s Basketball', null),
  ('old-weight-room', 3, '16:00', '17:30', 'Women''s Basketball', 'Women''s Basketball', null),
  ('gymnasium', 4, '16:00', '17:30', 'Women''s Basketball', 'Women''s Basketball', null),
  ('gymnasium', 5, '16:00', '17:30', 'Women''s Basketball', 'Women''s Basketball', null),
  ('old-weight-room', 1, '17:30', '19:00', 'Men''s Basketball', 'Men''s Basketball', null),
  ('gymnasium', 2, '17:30', '19:00', 'Men''s Basketball', 'Men''s Basketball', null),
  ('old-weight-room', 3, '17:30', '19:00', 'Men''s Basketball', 'Men''s Basketball', null),
  ('gymnasium', 4, '17:30', '19:00', 'Men''s Basketball', 'Men''s Basketball', null),
  ('gymnasium', 5, '17:30', '19:00', 'Men''s Basketball', 'Men''s Basketball', null),
  ('gymnasium', 1, '19:00', '20:30', 'Women''s Volleyball', 'Women''s Volleyball', null),
  ('old-weight-room', 2, '19:00', '20:30', 'Women''s Volleyball', 'Women''s Volleyball', null),
  ('gymnasium', 3, '19:00', '20:30', 'Women''s Volleyball', 'Women''s Volleyball', null),
  ('old-weight-room', 4, '19:00', '20:30', 'Women''s Volleyball', 'Women''s Volleyball', null),
  ('gymnasium', 5, '19:00', '20:30', 'Women''s Volleyball', 'Women''s Volleyball', null),
  ('gymnasium', 1, '20:30', '22:00', 'Men''s Volleyball', 'Men''s Volleyball', null),
  ('old-weight-room', 2, '20:30', '22:00', 'Men''s Volleyball', 'Men''s Volleyball', null),
  ('gymnasium', 3, '20:30', '22:00', 'Men''s Volleyball', 'Men''s Volleyball', null),
  ('old-weight-room', 4, '20:30', '22:00', 'Men''s Volleyball', 'Men''s Volleyball', null),
  ('gymnasium', 5, '20:30', '22:00', 'Men''s Volleyball', 'Men''s Volleyball', null),
  ('gymnasium', 2, '19:00', '21:30', 'Table Tennis', 'Table Tennis', null),
  ('gymnasium', 4, '19:00', '21:30', 'Table Tennis', 'Table Tennis', null),
  ('gymnasium', 2, '21:30', '23:00', 'Badminton', 'Badminton', null),
  ('gymnasium', 4, '21:30', '23:00', 'Badminton', 'Badminton', null),
  ('martial-arts-room', 1, '20:00', '22:00', 'Boxing Club', 'Boxing Club', null),
  ('martial-arts-room', 4, '20:00', '22:00', 'Boxing Club', 'Boxing Club', null),
  ('martial-arts-room', 2, '18:00', '20:00', 'Fight Camp', 'Fight Camp', null),
  ('martial-arts-room', 4, '18:00', '20:00', 'Fight Camp', 'Fight Camp', null),
  ('martial-arts-room', 5, '19:00', '20:00', 'Fight Camp', 'Fight Camp', null),
  ('martial-arts-room', 2, '20:00', '22:00', 'Kick Boxing', 'Kick Boxing', null),
  ('martial-arts-room', 4, '20:00', '22:00', 'Kick Boxing', 'Kick Boxing', null),
  ('martial-arts-room', 5, '20:00', '21:00', 'Kick Boxing', 'Kick Boxing', null),
  ('padel-court', 1, '20:00', '22:00', 'Padel', 'Padel', null),
  ('padel-court', 2, '20:00', '22:00', 'Padel', 'Padel', null),
  ('padel-court', 3, '20:00', '22:00', 'Padel', 'Padel', null),
  ('padel-court', 4, '20:00', '22:00', 'Padel', 'Padel', null),
  ('soccer-field', 1, '20:00', '22:00', 'Football Team A', 'Football Team A', null),
  ('soccer-field', 3, '20:00', '22:00', 'Football Team A', 'Football Team A', null),
  ('soccer-field', 2, '20:00', '22:00', 'Football Team B', 'Football Team B', null),
  ('soccer-field', 4, '20:00', '22:00', 'Football Team B', 'Football Team B', null),
  ('soccer-field', 1, '22:00', '23:30', 'Rugby', 'Rugby', null),
  ('soccer-field', 3, '22:00', '23:30', 'Rugby', 'Rugby', null),
  ('soccer-field', 2, '22:00', '23:30', 'American Football', 'American Football', null),
  ('soccer-field', 4, '22:00', '23:30', 'American Football', 'American Football', null)
) v(fac, d, s, e, act, team, note)
join public.facilities f on f.slug = v.fac left join public.teams t on t.name = v.team;

insert into public.booking_resources (slug, name, kind, facility_id, capacity, slot_minutes, same_day_only, min_notice_hours, allowed_roles, sort)
select v.slug, v.name, v.kind, f.id, v.cap, v.slot, v.same_day, v.notice, coalesce(v.roles::public.app_role[], '{super_admin,admin,coach,player,student}'), v.sort from (values
  ('bikes', 'Bikes', 'bike', null, 10, 60, true, 0, null, 1),
  ('padel', 'Padel Court', 'padel', 'padel-court', 1, 60, true, 0, null, 2),
  ('tennis-1', 'Tennis Court 1', 'tennis', 'tennis-court-1', 1, 60, true, 0, null, 3),
  ('tennis-2', 'Tennis Court 2', 'tennis', 'tennis-court-2', 1, 60, true, 0, null, 4),
  ('ice-bath', 'Ice Bath', 'ice_bath', null, 1, 30, false, 24, '{super_admin,admin,coach,player}', 5),
  ('sauna', 'Sauna', 'sauna', null, 4, 60, false, 0, '{super_admin,admin,coach,player}', 6)
) v(slug, name, kind, fac, cap, slot, same_day, notice, roles, sort)
left join public.facilities f on f.slug = v.fac;

insert into public.players (team_id, full_name, position, jersey_number, team_role)
select t.id, v.n, v.p, v.num, v.r from (values
  ('Oumnia Rida', 'Outside Hitter', 9::int, 'Captain'),
  ('Rim Namiri', 'Setter', 2::int, 'Vice Captain'),
  ('Zineb Andaloussi', 'Setter', null::int, null),
  ('Meryem Ahmedechrif', 'Outside Hitter', null::int, null),
  ('Rim Maouni', 'Outside Hitter', null::int, null),
  ('Hajar Ouardighi', 'Outside Hitter', 13::int, null),
  ('Weam Rochdi', 'Outside Hitter', 15::int, null),
  ('Nourane Benmansour', 'Middle Blocker', 3::int, null),
  ('Amal Kabbaj', 'Middle Blocker', 5::int, null),
  ('Riham', 'Middle Blocker', null::int, null),
  ('Hiba', 'Opposite Hitter', null::int, null),
  ('Iman El Isamy', 'Opposite Hitter', 10::int, null),
  ('Aya Kamili', 'Libero', 1::int, null),
  ('Alaa', 'Libero', null::int, null)
) v(n, p, num, r) cross join public.teams t where t.name = 'Women''s Volleyball';

insert into public.physical_tests (team_id, player_id, athlete_name, session_label, beep_stage, agility_t1, agility_t2,
  illinois_t1, illinois_t2, sprint_t1, sprint_t2, laps, best_agility, best_illinois, best_sprint, distance_m,
  score_beep, score_agility, score_illinois, score_sprint, score_distance, composite, rank, passed, notes)
select t.id, p.id, v.n, '1st Physical Testing', v.beep, v.a1, v.a2, v.i1, v.i2, v.s1, v.s2, v.laps, v.ba, v.bi, v.bs, v.dist,
  v.sb, v.sa, v.si, v.ss, v.sd, v.comp, v.rk, v.ok, v.note from (values
  ('Aya', 'Aya Kamili', 7.0, 4.35, 4.29, 16.31, 16.2, 5.41, 5.66, 7.5, 4.29, 16.2, 5.41, 150, 10.0, 6.79, 7.02, 7.31, 6.67, 7.56, 1, true, null),
  ('Rim', 'Rim Namiri', 5.7, 4.25, 4.35, 17.03, 15.81, 5.73, 6.86, 8, 4.25, 15.81, 5.73, 160, 5.19, 7.55, 7.73, 4.62, 10.0, 7.02, 2, true, null),
  ('Riham', 'Riham', 6.0, 4.19, 4.19, 17.22, 16.58, 5.81, 5.09, 6.5, 4.19, 16.58, 5.09, 130, 6.3, 8.68, 6.32, 10.0, 0.0, 6.26, 3, true, null),
  ('Meryem', 'Meryem Ahmedechrif', 5.0, 4.18, 4.19, 16.65, 16.23, 5.46, 5.34, 7, 4.18, 16.23, 5.34, 140, 2.59, 8.87, 6.96, 7.9, 3.33, 5.93, 4, true, null),
  ('Hiba', 'Hiba', 4.4, 4.39, 4.15, 16.76, 16.2, 5.35, 5.42, 7, 4.15, 16.2, 5.35, 140, 0.37, 9.43, 7.02, 7.82, 3.33, 5.59, 5, true, null),
  ('Hossna', null, 7.0, 4.42, 4.35, 16.58, 16.61, 6.16, 6.02, 7, 4.35, 16.58, 6.02, 140, 10.0, 5.66, 6.32, 2.18, 3.33, 5.5, 6, true, 'Tested athlete not on the current roster'),
  ('Oumnia', 'Oumnia Rida', 4.3, 4.33, 4.19, 14.58, 14.91, 5.64, 5.64, 7, 4.19, 14.58, 5.64, 140, 0.0, 8.68, 10.0, 5.38, 3.33, 5.48, 7, true, null),
  ('Sara', null, 4.4, 4.12, 4.12, 15.45, 17.91, 5.6, 5.64, 6.5, 4.12, 15.45, 5.6, 130, 0.37, 10.0, 8.4, 5.71, 0.0, 4.9, 8, true, 'Tested athlete not on the current roster'),
  ('Amal', 'Amal Kabbaj', 4.4, 4.56, 4.42, 19.05, 19.15, 6.0, 5.88, 7, 4.42, 19.05, 5.88, 140, 0.37, 4.34, 1.77, 3.36, 3.33, 2.63, 9, false, null),
  ('Lilya', null, 4.4, 4.72, 4.65, 20.01, 20.17, 6.28, 6.31, 6.5, 4.65, 20.01, 6.28, 130, 0.37, 0.0, 0.0, 0.0, 0.0, 0.07, 10, false, 'Tested athlete not on the current roster')
) v(n, roster, beep, a1, a2, i1, i2, s1, s2, laps, ba, bi, bs, dist, sb, sa, si, ss, sd, comp, rk, ok, note)
cross join public.teams t left join public.players p on p.full_name = v.roster and p.team_id = t.id
where t.name = 'Women''s Volleyball';

-- One test practice session with everyone marked present
with s as (insert into public.practice_sessions (team_id, session_date, title, notes)
  select id, date '2026-09-22', 'Practice', 'Test session — everyone present' from public.teams where name = 'Women''s Volleyball' returning id, team_id)
insert into public.attendance (session_id, player_id, status)
select s.id, p.id, 'present' from s join public.players p on p.team_id = s.team_id;

-- Default KPIs for the volleyball team (coaches can add their own)
insert into public.kpis (team_id, name, unit, target, higher_is_better)
select t.id, v.n, v.u, v.tg, v.h from (values ('Serve accuracy', '%', 85, true), ('Attack efficiency', '%', 30, true),
  ('Reception quality', '/3', 2.2, true), ('Vertical jump', 'cm', 45, true)) v(n, u, tg, h)
cross join public.teams t where t.name = 'Women''s Volleyball';
